=== MIND-Tools/mindtest/src/main/resources/org/ow2/mind/test/mind_test_v1.dtd
<!--
  Copyright (C) 2009 STMicroelectronics

 This file is part of "Mind Compiler" is free software: you can redistribute 
 it and/or modify it under the terms of the GNU Lesser General Public License 
 as published by the Free Software Foundation, either version 3 of the 
 License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful, but WITHOUT 
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
 details.

 You should have received a copy of the GNU Lesser General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 Contact: mind@ow2.org

 Authors: Matthieu Leclercq
 Contributors: 

 -->

<!-- *********************************************************************** -->
<!-- Basic AST structure                                                     -->
<!-- *********************************************************************** -->

<?add ast="testset" itf="org.ow2.mind.test.ast.TestSet" ?>
<?add ast="test"    itf="org.ow2.mind.test.ast.Test" ?>
<?add ast="config"  itf="org.ow2.mind.test.ast.Config" ?>
<?add ast="command" itf="org.ow2.mind.test.ast.Command" ?>
<?add ast="mindc"   itf="org.ow2.mind.test.ast.Mindc" ?>
<?map ast="mindc"   type="command" ?>


<!-- *********************************************************************** -->
<!-- Node grammar                                                            -->
<!-- *********************************************************************** -->

<!ELEMENT testset (config*, test*) >
<!ATTLIST testset
  name CDATA #REQUIRED
  nbJobs CDATA #IMPLIED
  runner CDATA #IMPLIED
>

<!ELEMENT test (config*) >
<!ATTLIST test
  name CDATA #REQUIRED
  adl CDATA #IMPLIED
  configRefs CDATA #IMPLIED
>

<!ELEMENT config ((command|mindc)*) >
<!ATTLIST config
  name CDATA #REQUIRED
  targetDescriptor CDATA #IMPLIED
>

<!ELEMENT command (#PCDATA) >
<!ATTLIST command
  dir CDATA #IMPLIED
  command CDATA #IMPLIED
>

<!ELEMENT mindc (#PCDATA) >
<!ATTLIST mindc
  dir      CDATA #IMPLIED
  command  CDATA #IMPLIED
  adl      CDATA #IMPLIED
  targetDescriptor CDATA #IMPLIED
  cFlags CDATA #IMPLIED
  ldFlags CDATA #IMPLIED
  execName CDATA #IMPLIED
>

=== MIND-Tools/mindtest/src/test/resources/unitTests/test1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testset SYSTEM
  "classpath://org/ow2/mind/test/mind_test_v1.dtd">

<testset name="testSuite1">
    <config name="conf1">
        <command>cmd1</command>
    </config>
    <config name="conf2" targetDescriptor="foo">
        <mindc />
        <command>cmd2</command>
    </config>
    <test name="test1" adl="foo.bar1" configRefs="conf2"/>
    <test name="test2" adl="foo.bar2" configRefs="conf1,conf2"/>
    <test name="test3" adl="foo.bar3" configRefs="all"/>
</testset>

=== MIND-Tools/mindtest/src/test/resources/integration/testset.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testset SYSTEM
  "classpath://org/ow2/mind/test/mind_test_v1.dtd">

<testset name="testSet">
    <config name="simple" targetDescriptor="simple">
        <mindc/>
        <command>${EXEC_NAME}</command>
    </config>
    
    <config name="optimize" targetDescriptor="simple">
        <mindc cFlags="-O3"/>
        <command>${EXEC_NAME}</command>
    </config>
    
    <config name="warning" targetDescriptor="simple">
        <mindc cFlags="-Wall -Werror"/>
        <command>${EXEC_NAME}</command>
    </config>
    
    <test name="test1" adl="foo.Bar" configRefs="all"/>
</testset>
